#!/usr/bin/env python3
"""Embed the single concert grand's measured resonance bank in the opcode."""
import argparse
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BEGIN = '/* BEGIN GENERATED PIANO RESONANCE DATA */'
END = '/* END GENERATED PIANO RESONANCE DATA */'


def load(name):
    return json.loads((ROOT/'fit'/name).read_text())


def generate():
    baseline = load('keyboard-modal-bank.json')
    assert [b['note'] for b in baseline['banks']] == list(range(23,108))
    assert [k['note'] for k in baseline['keys']] == list(range(21,109))
    banks = {b['note']: dict(b) for b in baseline['banks']}
    refinements = load('keyboard-treble-refinement.json')
    for bank in refinements['banks']:
        label = bank['note']
        note = int(baseline['recording_label_corrections'].get(str(label), label))
        assert note not in baseline['listening_feedback']['prior_individually_accepted_notes']
        banks[note] = {**bank, 'note': note, 'modes': [
            [m[k] for k in ('frequency_hz','loss_per_second','real','imag')]
            for c in bank['clusters'] for m in c['modes']]}
    ordered = [banks[n] for n in sorted(banks)]
    indices = {b['note']: i for i,b in enumerate(ordered)}
    extra = {}
    for case in load('modal-extension.json')['cases']:
        if case['dynamic'] == 'mf': continue
        assert case['note'] == 72
        extra[case['dynamic']] = len(ordered)
        ordered.append({'gain': case['native_check']['comparison_gain'],
                        'trim_initial': 1., 'trim_seconds': 0.,
                        'modes': [[m[k] for k in ('frequency_hz','loss_per_second','real','imag')]
                                  for c in case['clusters'] for m in c['modes']]})
    assert set(extra) == {'pp','ff'}
    modes, entries = [], []
    for bank in ordered:
        assert bank['modes'] and 0 < bank['gain'] < 100
        assert math.isfinite(bank['trim_initial']) and 0 <= bank['trim_initial'] <= 4
        assert math.isfinite(bank['trim_seconds']) and 0 <= bank['trim_seconds'] <= 1
        entries.append([len(modes),len(bank['modes']),bank['gain'],bank['trim_initial'],bank['trim_seconds']])
        for mode in bank['modes']:
            assert len(mode) == 4 and all(math.isfinite(x) for x in mode)
            assert 0 < mode[0] < 20000 and .0 < mode[1] <= 80
            modes.append(mode)
    keys = [[indices[k['bank_note']],k['frequency_ratio'],k['gain']] for k in baseline['keys']]
    velocity = load('keyboard-velocity.json')
    assert [k['note'] for k in velocity['keys']] == list(range(21,109))
    curves = [k['excitation_db'][d] for k in velocity['keys'] for d in ('pp','ff')]
    assert all(len(c) == len(velocity['frequency_ratios']) and
               all(math.isfinite(x) and abs(x) <= 18 for x in c) for c in curves)
    decay = load('keyboard-dynamic-decay.json')
    for name, expected in decay['input_hashes'].items():
        assert hashlib.sha256((ROOT/'fit'/name).read_bytes()).hexdigest() == expected, name+' changed; refit dynamic damping'
    assert [k['note'] for k in decay['keys']] == list(range(21,109))
    decay_keys, decay_groups, decay_factors = [], [], []
    for key, fitted in zip(baseline['keys'], decay['keys']):
        count = len(banks[key['bank_note']]['modes'])
        groups = [None] * count
        gains = [fitted['normalization_gain'][d] for d in ('pp','ff')]
        assert all(math.isfinite(v) and .25 < v < 4 for v in gains)
        decay_keys.append([len(decay_groups), *gains])
        for group in fitted['groups']:
            factors = [group['loss_scale'][d] for d in ('pp','ff')]
            assert all(math.isfinite(v) and .5 <= v <= 2 for v in factors)
            if key['note'] == 72:
                assert factors == [1., 1.] and gains == [1., 1.]
            for i in group['mode_indices']:
                assert 0 <= i < count and groups[i] is None
                groups[i] = len(decay_factors)
            decay_factors.append(factors)
        assert all(g is not None for g in groups)
        decay_groups.extend(groups)
    assert len(decay_factors) < 65536
    maximum = max(3*max(len(b['modes']) for b in ordered[:85]),
                  sum(len(ordered[i]['modes']) for i in (indices[72],extra['pp'],extra['ff'])))
    text = BEGIN+'\n/* Generated by tools/generate_modal_bank.py; edit the fit data. */\n'
    text += f'#define WG_MODAL_CAPACITY {maximum}U\n'
    text += f'#define WG_MODAL_C5_PP {extra["pp"]}U\n#define WG_MODAL_C5_FF {extra["ff"]}U\n'
    text += f'#define WG_VELOCITY_BANDS {len(velocity["frequency_ratios"])}U\n'
    text += 'typedef struct { unsigned offset, count; double gain, initial, seconds; } WG_MODAL_BANK;\n'
    text += 'typedef struct { unsigned bank; double ratio, gain; } WG_MODAL_KEY;\n'
    text += 'typedef struct { unsigned offset; double pp_gain, ff_gain; } WG_MODAL_DECAY;\n'
    for name,kind,rows,suffix in [
            ('wg_modal_modes','double',modes,'[4]'),
            ('wg_modal_banks','WG_MODAL_BANK',entries,''),
            ('wg_modal_keys','WG_MODAL_KEY',keys,''),
            ('wg_velocity_curves','double',curves,'[WG_VELOCITY_BANDS]'),
            ('wg_velocity_normalizations','double',[[k['normalization_gain'][d] for d in ('pp','ff')]
                                                   for k in velocity['keys']],'[2]'),
            ('wg_modal_decay_keys','WG_MODAL_DECAY',decay_keys,''),
            ('wg_modal_decay_factors','double',decay_factors,'[2]')]:
        text += f'static const {kind} {name}[{len(rows)}]{suffix} = {{\n'
        text += ',\n'.join(' {'+', '.join(format(v,'.17g') for v in row)+'}' for row in rows)+'\n};\n'
    text += 'static const double wg_velocity_ratios[WG_VELOCITY_BANDS] = {'
    text += ', '.join(format(v,'.17g') for v in velocity['frequency_ratios'])+'};\n'
    text += f'static const uint16_t wg_modal_decay_groups[{len(decay_groups)}] = {{\n'
    text += ',\n'.join(' '+', '.join(str(v) for v in decay_groups[i:i+24])
                       for i in range(0,len(decay_groups),24))+'\n};\n'
    return text+END


def main():
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument('--check', action='store_true')
    args = cli.parse_args()
    source = ROOT/'hlolli_wg_piano.c'
    original = source.read_text()
    block = generate()
    if BEGIN in original:
        start,end = original.index(BEGIN),original.index(END)+len(END)
        result = original[:start]+block+original[end:]
    else:
        marker = '/* END GENERATED PIANO PROFILE DATA */'
        result = original.replace(marker,marker+'\n\n'+block,1)
    if len(result.encode()) > 2*1024*1024:
        raise SystemExit('Embedded source exceeds the browser compiler\'s 2 MiB limit.')
    if args.check:
        if result != original: raise SystemExit('Embedded resonance data is stale.')
        print('Embedded resonance data matches the fit inputs.')
    else:
        source.write_text(result)
        print('Embedded resonance data:',len(block.encode()),'bytes')


if __name__ == '__main__': main()
